### ISSUE TITLE
hubconf.py?

### ISSUE THREAD

**Issue by chriscrutt** [Choru5/ML-Aimbot-Halo-Infinite#1]
So I did everything but end up getting that there is no file hubconf.py (which there isn't haha).

Steps to recreate:

1. download repo
2. install anaconda
3. open as admin and cd into directory
4. install pytorch and cuda `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`
 5. Create a venv `conda create -n pytorch-gpu python==3.8`
 6. Activate venv `conda activate pytorch-gpu`
 7. install requirements (had to change ` torch==1.11.0+cu113` in requirements file to just `torch==1.11.0` and such because I was getting
 ```
ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.11.0+cu113
```
 19. ran `python deploy.py`
that's when I got
```
[INFO] Loading model...
Traceback (most recent call last):
  File "deploy.py", line 222, in <module>
    main(run_loop=True, vid_out="example.mp4")
  File "deploy.py", line 138, in main
    model = torch.hub.load('./yolov5', 'custom', source ='local', path=modelFile, force_reload=True)
  File "C:\Users\chris\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\chris\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 430, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "C:\Users\chris\anaconda3\envs\pytorch-gpu\lib\site-packages\torch\hub.py", line 76, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: './yolov5\\hubconf.py'
```
Running Windows 10 if you haven't guessed

**Comment by chriscrutt** [comment]
got it to work by cloning [yolo5](https://github.com/ultralytics/yolov5/tree/8a4175cde0702285a9ba2fea4fb94aa8bd745754) duh
